global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: account-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["account:8090"]
        labels:
          application: account-service

  - job_name: payment-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["payment:8091"]
        labels:
          application: payment-service

  - job_name: cashback-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["cashback:8092"]
        labels:
          application: cashback-service

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification:8093"]
        labels:
          application: notification-service
